### PR TITLE
Fixed typo `fs_mount` vs `fsmount`

### PR DESCRIPTION
**Pull request by hnj2**
I think there was a small typo with the seccomp profile creation.

The project wouldn't compile on my ubuntu 20.04.1 based system with the error message:
```
  CC       libswtpm_libtpms_la-seccomp_profile.lo
In file included from seccomp_profile.c:44:
seccomp_profile.c: In function ‘create_seccomp_profile’:
seccomp_profile.c:105:9: error: ‘__SNR_fs_mount’ undeclared (first use in this function)
  105 |         SCMP_SYS(fs_mount),
      |         ^~~~~~~~
seccomp_profile.c:105:9: note: each undeclared identifier is reported only once for each function it appears in
```

My guess is that this is simply a typo and `fs_mount` was supposed to be `fsmount`.

**Note:** I have no previous expertise with seccomp, so please double check. Maybe `fs_mount` is a valid name that is just not available on my non-cutting-edge system.

**Note 2:** There are some identifiers that are used multiple times in the SCMP_SYS macro, namely `fsmount` and `move_mount`. Is this intentional?

### CODE REVIEW

**Comment by stefanberger** [comment]
You are right. Do you want to update your commit with your Signed-off-by and just state that it fixes a typo in the sycall name fsmount? Thanks.

**Comment by stefanberger** [comment]
And please prefix the commit header with `swtpm:`.

File: src/swtpm/seccomp_profile.c [hunk 1]
```diff
@@ -102,7 +102,7 @@ int create_seccomp_profile(bool cusetpm, unsigned int action)
         SCMP_SYS(fsconfig),
 #endif
 #ifdef __NR_fsmount
-        SCMP_SYS(fs_mount),
+        SCMP_SYS(fsmount),
```
Comment (stefanberger) [inline src/swtpm/seccomp_profile.c:105]: Most of the commit text can go. Just leave this part:
```
The project wouldn't compile on my ubuntu 20.04.1 based system with the error message:
```
  CC       libswtpm_libtpms_la-seccomp_profile.lo
In file included from seccomp_profile.c:44:
seccomp_profile.c: In function ‘create_seccomp_profile’:
seccomp_profile.c:105:9: error: ‘__SNR_fs_mount’ undeclared (first use in this function)
  105 |         SCMP_SYS(fs_mount),
      |         ^~~~~~~~
seccomp_profile.c:105:9: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Hans Niklas Jacob <hnj@posteo.de>
```

**Comment by stefanberger** [comment]
Thanks.
